### ISSUE TITLE
Join the CLI commands

### ISSUE THREAD

**Issue by thiderman** [thiderman/piper#38]
Basically, is there a need to have a `piperd`? The split was made to separate the *building* parts from the *backend* parts, but I'm growing more fond of the idea of having just *the one* CLI entry point.

@daenney, what do you think?

**Comment by daenney** [comment]
The idea is that everything will work through the API right? So theoretically speaking any interaction you want to do as the client will simply be `piper <something something>`.

The only thing we need to make sure is that you can do something like `piper server` to actually start piperd.

**Comment by thiderman** [comment]
Exactly so. I'll work on this right away. Niceness abound! :+1:
